### ISSUE TITLE
error with underscore in lstlisting

### ISSUE THREAD

**Issue by JonathanStarup** [flix/latex-flix#1]
Something goes wrong in the idstyle command when there is an underscore in the code.

```latex
\documentclass{article}

\usepackage{flix}
\lstset{language=flix}

\begin{document}

\begin{lstlisting}
let _ = 42
\end{lstlisting}

\end{document}
```

**Comment by JonathanStarup** [comment]
@magnus-madsen what is the problem with `identifierstyle   = \color{identifier-color}`? It seems to work fine for me. Also - is it intentional that identifiers are the same color as the comments (rgb 55 55 55)?

**Comment by magnus-madsen** [comment]
No idea for either question :)
