### ISSUE TITLE
Update keywords

### ISSUE THREAD

**Issue by magnus-madsen** [flix/latex-flix#7]
Update the keywords in `flix.sty` to reflect current keywords.

**Comment by magnus-madsen** [comment]
@sockmaster27 @jaschdoc Could I ask either of you to do this. The task has some urgency, so first to do it, gets it.

**Comment by magnus-madsen** [comment]
It might also be good to add an empty latex document with some Flix code in it, so one can "visually test" that it works.

The code could come from the samples or from doc.flix.dev etc.

**Comment by magnus-madsen** [comment]
To find the keywords, look at `Parser.scala` or at VSCode etc.

**Comment by magnus-madsen** [comment]
Please also remove old keywords.

**Comment by magnus-madsen** [comment]
Is see there is already `example.tex` so that can simply be expanded.

**Comment by jaschdoc** [comment]
I think maybe we can just copy paste the keywords from the higlightjs repository?

**Comment by magnus-madsen** [comment]
Sure, anything that is up to date.
